apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sm-workflow-approval
  namespace: sm
spec:
  podSelector:
    matchLabels:
      app: sm-workflow-approval
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          platform: sm-suite
    ports:
    - protocol: TCP
      port: 8350
  - from:
    - podSelector:
        matchLabels:
          app: sm-api-gateway
    ports:
    - protocol: TCP
      port: 8350
  egress:
  - to:
    - podSelector:
        matchLabels:
          platform: sm-suite
    ports:
    - protocol: TCP
      port: 8320
    - protocol: TCP
      port: 8470
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
