apiVersion: v1
kind: Service
metadata:
  name: sm-workflow-approval
  namespace: sm-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8300
      targetPort: http
  selector:
    app: sm-workflow-approval
