"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:11:29.494285
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wf_chains',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('applicant', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_node_index', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wf_chains_applicant'), 'wf_chains', ['applicant'], unique=False)
    op.create_index(op.f('ix_wf_chains_status'), 'wf_chains', ['status'], unique=False)
    op.create_index(op.f('ix_wf_chains_title'), 'wf_chains', ['title'], unique=False)
    op.create_index(op.f('ix_wf_chains_workflow_id'), 'wf_chains', ['workflow_id'], unique=False)
    op.create_table('wf_nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=16), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wf_nodes_workflow_id'), 'wf_nodes', ['workflow_id'], unique=False)
    op.create_table('wf_workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wf_workflows_code'), 'wf_workflows', ['code'], unique=True)
    op.create_index(op.f('ix_wf_workflows_status'), 'wf_workflows', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wf_workflows_status'), table_name='wf_workflows')
    op.drop_index(op.f('ix_wf_workflows_code'), table_name='wf_workflows')
    op.drop_table('wf_workflows')
    op.drop_index(op.f('ix_wf_nodes_workflow_id'), table_name='wf_nodes')
    op.drop_table('wf_nodes')
    op.drop_index(op.f('ix_wf_chains_workflow_id'), table_name='wf_chains')
    op.drop_index(op.f('ix_wf_chains_title'), table_name='wf_chains')
    op.drop_index(op.f('ix_wf_chains_status'), table_name='wf_chains')
    op.drop_index(op.f('ix_wf_chains_applicant'), table_name='wf_chains')
    op.drop_table('wf_chains')
    # ### end Alembic commands ###
