# Service: ClusterIP，targetPort 对应业务端口 8028
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sm-workflow-approval.fullname" . }}
  labels:
    {{- include "sm-workflow-approval.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sm-workflow-approval.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
