# ServiceAccount: sm-workflow-approval
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-workflow-approval.serviceAccountName" . }}
  labels:
    {{- include "sm-workflow-approval.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
